src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Models/RemoteClient.cs
namespace OrchardCore.Deployment.Remote.Models
{
    public class RemoteClient
    {
        public string Id { get; set; }
        public string ClientName { get; set; }
        public byte[] ProtectedApiKey { get; set; }
    }
}

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Controllers/ImportRemoteInstanceController.cs
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.FileProviders;
using OrchardCore.Deployment.Remote.Services;
using OrchardCore.Deployment.Remote.ViewModels;
using OrchardCore.Deployment.Services;

namespace OrchardCore.Deployment.Remote.Controllers
{
    public class ImportRemoteInstanceController : Controller
    {
        private readonly RemoteClientService _remoteClientService;
        private readonly IDeploymentManager _deploymentManager;
        private readonly IDataProtector _dataProtector;

        public ImportRemoteInstanceController(
            IDataProtectionProvider dataProtectionProvider,
            RemoteClientService remoteClientService,
            IDeploymentManager deploymentManager,
            IHtmlLocalizer<ExportRemoteInstanceController> h)
        {
            _deploymentManager = deploymentManager;
            _remoteClientService = remoteClientService;
            _dataProtector = dataProtectionProvider.CreateProtector("OrchardCore.Deployment").ToTimeLimitedDataProtector();
            H = h;
        }

        public IHtmlLocalizer H { get; }

        /// <remarks>
        /// We ignore the AFT as the service is called from external applications (they can't have valid ones) and 
        /// we use a private API key to secure its calls.
        /// </remarks>
        [HttpPost]
        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> Import(ImportViewModel model)
        {
            var remoteClientList = await _remoteClientService.GetRemoteClientListAsync();

            var remoteClient = remoteClientList.RemoteClients.FirstOrDefault(x => x.ClientName == model.ClientName);

            var apiKey = Encoding.UTF8.GetString(_dataProtector.Unprotect(remoteClient.ProtectedApiKey));

            if (remoteClient == null || model.ApiKey != apiKey || model.ClientName != remoteClient.ClientName)
            {
                return StatusCode((int)HttpStatusCode.BadRequest, "The Api Key was not recognized");
            }

            // Create a temporary filename to save the archive
            var tempArchiveName = Path.GetTempFileName() + ".zip";

            // Create a temporary folder to extract the archive to
            var tempArchiveFolder = PathExtensions.Combine(Path.GetTempPath(), Path.GetRandomFileName());

            try
            {
                using (var fs = System.IO.File.Create(tempArchiveName))
                {
                    await model.Content.CopyToAsync(fs);
                }

                ZipFile.ExtractToDirectory(tempArchiveName, tempArchiveFolder);

                await _deploymentManager.ImportDeploymentPackageAsync(new PhysicalFileProvider(tempArchiveFolder));
            }
            finally
            {
                if (System.IO.File.Exists(tempArchiveName))
                {
                    System.IO.File.Delete(tempArchiveName);
                }

                if (Directory.Exists(tempArchiveFolder))
                {
                    Directory.Delete(tempArchiveFolder, true);
                }
            }

            return Ok();
        }
    }
}

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Controllers/RemoteClientController.cs
using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using OrchardCore.Admin;
using OrchardCore.Deployment.Remote.Services;
using OrchardCore.Deployment.Remote.ViewModels;
using OrchardCore.DisplayManagement.Notify;
using YesSql;

namespace OrchardCore.Deployment.Remote.Controllers
{

    [Admin]
    public class RemoteClientController : Controller
    {
        private readonly IDataProtector _dataProtector;
        private readonly IAuthorizationService _authorizationService;
        private readonly ISession _session;
        private readonly INotifier _notifier;
        private readonly RemoteClientService _service;

        public RemoteClientController(
            IDataProtectionProvider dataProtectionProvider,
            RemoteClientService service,
            IAuthorizationService authorizationService,
            ISession session,
            IStringLocalizer<RemoteClientController> stringLocalizer,
            IHtmlLocalizer<RemoteClientController> htmlLocalizer,
            INotifier notifier
            )
        {
            _session = session;
            _authorizationService = authorizationService;
            S = stringLocalizer;
            H = htmlLocalizer;
            _notifier = notifier;
            _service = service;
            _dataProtector = dataProtectionProvider.CreateProtector("OrchardCore.Deployment").ToTimeLimitedDataProtector();
        }

        public IStringLocalizer S { get; set; }
        public IHtmlLocalizer H { get; set; }

        public async Task<IActionResult> Index()
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Unauthorized();
            }

            var remoteClientList = await _service.GetRemoteClientListAsync();
            
            var model = new RemoteClientIndexViewModel
            {
                RemoteClientList = remoteClientList
            };

            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Unauthorized();
            }

            var model = new EditRemoteClientViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EditRemoteClientViewModel model)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                ValidateViewModel(model);
            }

            if (ModelState.IsValid)
            {
                await _service.CreateRemoteClientAsync(model.ClientName, model.ApiKey);

                _notifier.Success(H["Remote client created successfully"]);
                return RedirectToAction(nameof(Index));
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Unauthorized();
            }

            var remoteClient = await _service.GetRemoteClientAsync(id);

            if (remoteClient == null)
            {
                return NotFound();
            }

            var model = new EditRemoteClientViewModel
            {
                Id = remoteClient.Id,
                ClientName = remoteClient.ClientName,
                ApiKey = Encoding.UTF8.GetString(_dataProtector.Unprotect(remoteClient.ProtectedApiKey)),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditRemoteClientViewModel model)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Unauthorized();
            }

            var remoteClient = await _service.GetRemoteClientAsync(model.Id);

            if (remoteClient == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                ValidateViewModel(model);
            }

            if (ModelState.IsValid)
            {
                await _service.TryUpdateRemoteClient(model.Id, model.ClientName, model.ApiKey);

                _notifier.Success(H["Remote client updated successfully"]);

                return RedirectToAction(nameof(Index));
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Unauthorized();
            }

            var remoteClient = await _service.GetRemoteClientAsync(id);

            if (remoteClient == null)
            {
                return NotFound();
            }

            await _service.DeleteRemoteClientAsync(id);

            _notifier.Success(H["Remote client deleted successfully"]);

            return RedirectToAction(nameof(Index));
        }

        private void ValidateViewModel(EditRemoteClientViewModel model)
        {
            if (String.IsNullOrWhiteSpace(model.ClientName))
            {
                ModelState.AddModelError(nameof(EditRemoteClientViewModel.ClientName), S["The client name is mandatory."]);
            }

            if (String.IsNullOrWhiteSpace(model.ApiKey))
            {
                ModelState.AddModelError(nameof(EditRemoteClientViewModel.ApiKey), S["The api key is mandatory."]);
            }
        }
    }
}

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Create.cshtml
@model EditRemoteClientViewModel

<div asp-validation-summary="ModelOnly"></div>
<form asp-action="Create" method="post">

    <div class="form-group" asp-validation-class-for="ClientName">
        <label asp-for="ClientName">@T["Client Name"]</label>
        <span asp-validation-for="ClientName" class="text-danger">@T["The client name is required."]</span>
        <input asp-for="ClientName" class="form-control" />
    </div>
        
    <div class="form-group" asp-validation-class-for="ApiKey">
        <label asp-for="ApiKey">@T["Api Key"]</label>
        <span asp-validation-for="ApiKey" class="text-danger">@T["The api key is required."]</span>
        <input asp-for="ApiKey" type="password" class="form-control" />
    </div>

    <fieldset>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">@T["Create"]</button>
            <a class="btn btn-secondary" asp-route-action="Index">@T["Cancel"]</a>
        </div>
    </fieldset>
</form>

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Edit.cshtml
@model EditRemoteClientViewModel

<h1>@RenderTitleSegments(T["Edit Remote Client"])</h1>

<div asp-validation-summary="ModelOnly"></div>
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group" asp-validation-class-for="ClientName">
        <label asp-for="ClientName">@T["Client Name"]</label>
        <span asp-validation-for="ClientName" class="text-danger">@T["The client name is required."]</span>
        <input asp-for="ClientName" class="form-control" />
    </div>

    <div class="form-group" asp-validation-class-for="ApiKey">
        <label asp-for="ApiKey">@T["Api Key"]</label>
        <span asp-validation-for="ApiKey" class="text-danger">@T["The api key is required."]</span>
        <input asp-for="ApiKey" type="password" class="form-control" value="@Model.ApiKey" />
    </div>

    <fieldset>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">@T["Save"]</button>
            <a class="btn btn-secondary" asp-route-action="Index">@T["Cancel"]</a>
        </div>
    </fieldset>
</form>

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Index.cshtml
@model RemoteClientIndexViewModel

<h1>@RenderTitleSegments(T["Remote Clients"])</h1>

<div class="alert alert-info" role="alert">
    @T["Url to use from client instances: <b>{0}</b>", Url.Action("Import", "ImportRemoteInstance", null, Context.Request.Scheme)]
</div>


<nav class="admin-toolbar">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a asp-route-action="Create" class="btn btn-primary" role="button">@T["Add Remote Client"]</a>
        </li>
    </ul>
</nav>

<form asp-action="Index"> @* the form is necessary to generate and antiforgery token for the delete action *@
    @if (Model.RemoteClientList.RemoteClients.Any())
    { 
        <ul class="list-group">
            @foreach (var entry in Model.RemoteClientList.RemoteClients)
            {
                <li class="list-group-item">
                    <div class="properties">
                        <div class="related">
                            <a asp-action="Edit" asp-route-id="@entry.Id" class="btn btn-primary btn-sm">@T["Edit"]</a>
                            <a asp-action="Delete" asp-route-id="@entry.Id" class="btn btn-danger btn-sm" itemprop="RemoveUrl UnsafeUrl">@T["Delete"]</a>
                        </div>
                        <h5>@entry.ClientName</h5>
                    </div>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="alert alert-info" role="alert">
            @T["<strong>Nothing here!</strong> There are no remote clients for the moment."]
        </div>
    }
</form>